# Generated by Django 5.0.6 on 2024-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=10)),
                ('course_description', models.TextField()),
                ('class_hours', models.PositiveSmallIntegerField()),
                ('prerequisites', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(max_length=100)),
                ('assessment_requirements', models.DateField()),
                ('school_term', models.PositiveSmallIntegerField()),
                ('course_capacity', models.PositiveSmallIntegerField()),
                ('grade_level', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
