# Generated by Django 5.0.6 on 2024-06-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_instructor',
        ),
    ]
