# Generated by Django 5.0.6 on 2024-07-22 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_class_hours_course_course_ahead_and_more'),
        ('teacher', '0003_rename_email_teacher_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teacher.teacher'),
        ),
    ]
