# Generated by Django 5.0.6 on 2024-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
