# Generated by Django 5.0.6 on 2024-06-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='Course',
            new_name='course',
        ),
    ]
