# Generated by Django 5.0.6 on 2024-07-22 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_rename_enrollement_class_class_enrollement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='course',
        ),
        migrations.RemoveField(
            model_name='class',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='class',
            name='class_speciality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
