# Generated by Django 5.0.6 on 2024-07-22 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_remove_class_course_remove_class_meeting_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_speciality',
        ),
        migrations.AddField(
            model_name='class',
            name='class_speaciality',
            field=models.TextField(default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
